### ISSUE TITLE
Adding macro via macro factory not working with local devices

### ISSUE THREAD

**Issue by cyprien3** [voipnorm/CE-Deploy#22]
reading macros and removing them works fine, adding does not, it tries forever.

This is on CE9.15.3, I could reproduce this on two different networks.

CE-Deploy 8.0

**Comment by voipnorm** [comment]
Tested both local and cloud macro factory and it works fine. Please provide the method you were trying to use.

**Comment by cyprien3** [comment]
It was local macro factory. Cloud macro factory on the same endpoint works fine.

**Comment by voipnorm** [comment]
Issue resolved

**Comment by RamosBruno** [comment]
Hi, 

I'm opening this issue because i'm having the same trouble in local mode.

When i try to add a macro to a device the ssh connection don't work because all the special chars are not escaped, the ssh connection fails and the WS connection works but don't upload the macro.

When I remove all special chars the macro is uploaded, in my case i need to remove : 

      '    /*var regex = /^sd_([a-zA-Z0-9@_\\-\\.]+)$/;*/\n' +
      '      var regex = /([a-zA-Z0-9@_\\-\\.]+)$/;\n' +

      `            helpPopUp("Besoin d'aide ?", "Grâce à ce bouton vous pourrez rejoindre une conférence. Pensez à vous munir de l'identifiant de la conférence");\n` +

Those lines come from the renderer.log
